- name: Install Nginx
- hosts: nginx-instance
  tasks: 
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install
      command: "pip install docker-py"    
   
    - name: Pull a Docker Image
      docker_image: 
         name: httpd
         tag: latest
         source: pull
      register: z
    - name: Checking Pull Status
      debug: 
        var: z
   
    - name: Creating a Persistent Volume Dir
      file:
        path: "/root/pv"
        state: directory
   
    - name: Copying the HTML code in the Directory
      copy: 
        src: "/root/Desktop/index.html"
        dest: "/root/pv"
   
    - name: Launching an HTTPD Container
      when: z.failed == false
      docker_container:
        name: apache-server
        image: httpd
        state: started
        exposed_ports:
          - "80"
        ports:
          - "8080:80"
        volumes: 
          - /root/pv:/usr/local/apache2/htdocs