---
- name: Install Nginx
  hosts: nginx-instance
  become: yes
  become_method: sudo

  tasks:

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/Dockerfile

    - name: Copy default.conf
      copy:
        src: ./default.conf
        dest: /tmp/default.conf
        
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install pip
      apt: 
       name: python3-pip 
       state: present
      
    - name: install docker
      pip: 
       name: docker
       executable: pip3

    - name: Pull nginx
      shell: docker pull nginx


    - name: Build custom container
      shell: docker build -t nginx_stats .
      args:
        chdir: /tmp/

    - name: Run Docker Nginx  
      shell: docker run --name nginx -d -p 8080:80 nginx_stats