---
- name: Install Nginx
  hosts: nginx-instance
  become: yes
  become_method: sudo

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install pip
      apt: 
       name: python3-pip 
       state: present
      
    - name: install docker
      pip: 
       name: docker
       executable: pip3

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/Dockerfile      

    - name: build container image
      docker_image:
        name: nginx-web-server:v1.0
        build:
          path: /tmp
        source: build
        state: present        

    - name: archive container image as a tarball
      docker_image:
        name: nginx-web-server:v1.0
        archive_path: /tmp/nginx-web-server_v1_0.tar
        source: pull
        state: present

    - name: fetch archived image
      fetch:
        src: /tmp/nginx-web-server_v1_0.tar
        dest: ./nginx-web-server_v1_0.tar
        flat: true

    - name: copy tarball to root
      copy:
        src: ./nginx-web-server_v1_0.tar
        dest: /root/nginx-web-server_v1_0.tar

    - name: load container from tarball
      docker_image:
        name: nginx-web-server:v1.0
        load_path: /root/nginx-web-server_v1_0.tar
        state: present
        source: load

    - name: Running the container
      docker_container:
        name: nginx-server
        image: nginx-web-server:v1.0
        state: started
#        healthcheck: 
#          test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#          interval: 1m30s
#          timeout: 10s
#          retries: 3
#          start_period: 30s
        