---
- name: Install Nginx
  hosts: nginx-instance
  become: yes
  become_method: sudo

  tasks:

    - name: Copy Dockerfile
      copy:
        src: ./terraform/playbooks/Dockerfile
        dest: /tmp/Dockerfile
  
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi

    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes

    - name: Install pip
      apt: 
       name: python3-pip 
       state: present
      
    - name: install docker
      pip: 
       name: docker
       executable: pip3
      
    - name: Build Docker image from Dockerfile
      docker_image:
        build: 
          path: /tmp/Dockerfile
        name: nginx-web-server
        source: build

    - name: Container present
      docker_container:
        name: nginx-web-server
        state: present
        image: nginx-web-server:latest
        command: sleep infinity
        

    - name: Running the container
      docker_container:
        image: nginx-web-server:latest
        state: started
        healthcheck: 
#          test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#          interval: 1m30s
#          timeout: 10s
#          retries: 3
#          start_period: 30s        