---
- name: Install Nginx
  hosts: nginx-instance
  become: yes
  become_method: sudo

  tasks:
    - name: Install pip
      apt: 
       name: python-pip 
       state: present
      
    - name: install docker-py
      pip: 
       name: docker-py
      
    - name: Build Docker image from Dockerfile
      docker_image:
        build: 
          path: ./
        name: nginx-web-server
        source: build

    - name: Container present
      docker_container:
        name: nginx-web-server
        state: present
        image: nginx-web-server:latest
        command: sleep infinity
        

    - name: Running the container
      docker_container:
        image: nginx-web-server:latest
        state: started
        healthcheck: 
#          test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#          interval: 1m30s
#          timeout: 10s
#          retries: 3
#          start_period: 30s        