---
- name: Install Nginx
  hosts: nginx-instance
  become: yes
  become_method: sudo

  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes
    - name: Configuring Docker Repository
      yum_repository:
        name: Docker
        description: "Docker Repo"
        baseurl: "https://download.docker.com/linux/centos/docker-ce.repo" 
        gpgcheck: no
      register: x
 
    - name: Checking Configuration Status
      debug:
        var: x.failed
 
    - name: Installing Docker
      package:
        name: "docker-ce-18.06.3.ce-3.el7.x86_64"
        state: present
      register: y
 
    - name: Checking Install Status
      debug:
        var: y.failed
 
    - name: Starting Docker Daemon
      service:
        name: docker
        state: started
        enabled: yes
      when: y.failed == false

    - name: Install pip
      apt: 
       name: python3-pip 
       state: present
      
    - name: install docker
      pip: 
       name: docker
       executable: pip3
      
    - name: Build Docker image from Dockerfile
      docker_image:
        build: 
          path: /tmp
        name: nginx-web-servers
        source: build

    - name: Container present
      docker_container:
        name: nginx-web-server
        state: present
        image: nginx-web-server:latest
        command: sleep infinity
        

    - name: Running the container
      community.general.docker_container:
        image: nginx-web-server:latest
        state: started
        healthcheck: 
#          test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#          interval: 1m30s
#          timeout: 10s
#          retries: 3
#          start_period: 30s        