name: Deploying application

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    - name: Workflow run cleanup action
      uses: rokroskar/workflow-run-cleanup-action@v0.2.2
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v1
    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.13.4"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget -q https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip -o -d terraform_"$tf_version"_linux_amd64.zip
        sudo mv -f terraform /usr/local/bin/
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false