name: Deploying workflow

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Verify Terraform version
      run: terraform --version

    - name: Generate Key Pair
      run: |
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/ec2_key_pair.pem -q -P ''
        chmod 400 ~/.ssh/ec2_key_pair.pem
        ssh-keygen -y -f ~/.ssh/ec2_key_pair.pem > ~/.ssh/ec2_key_pair.pub
        
    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false
