name: Deploying workflow

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Verify Terraform version
      run: terraform --version

    - name: Assigning Influx IP adress to Environment Variable
      run: |
        echo "TF_VAR_influxdb_url=http://$(~/.local/bin/aws ec2 describe-instances \
        --filters "Name=tag:Name,Values=grafana-instance" \
        --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
        --output text):8086" >> $GITHUB_ENV
    - name: Check if environment Applied successfully
      run: echo $TF_VAR_influxdb_url

    - name: Generate Key Pair
      env:
        EC2_KEY_PEM_64: ${{ secrets.EC2_KEY_PEM_64 }}
        EC2_KEY_PUB_64: ${{ secrets.EC2_KEY_PUB_64 }}
      run: |
        mkdir -p ~/.ssh
        echo $EC2_KEY_PEM_64 | openssl base64 -A -d > ~/.ssh/ec2_key_pair.pem 
        chmod 400 ~/.ssh/ec2_key_pair.pem
        echo $EC2_KEY_PUB_64 | openssl base64 -A -d > ~/.ssh/ec2_key_pair.pub
        chmod 644 ~/.ssh/ec2_key_pair.pub
    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_influxdb_user_password: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      run: terraform init -input=false

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_influxdb_user_password: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      run: |
      
        terraform plan
      
    - name: Terraform validation
      run: terraform validate

    - name: Terraform Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_influxdb_user_password: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      run: terraform apply -auto-approve -input=false
